// Mocks generated by Mockito 5.4.4 from annotations
// in food_recipe/test/screen/splash_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i12;

import 'package:food_recipe/core/domain/entities/storage_user.dart' as _i8;
import 'package:food_recipe/core/domain/entities/user.dart' as _i3;
import 'package:food_recipe/features/splash/data/repository/splash_repository_impl.dart'
    as _i5;
import 'package:food_recipe/features/splash/domain/repository/splash_repository.dart'
    as _i4;
import 'package:food_recipe/features/splash/domain/usecases/storage_get_user.dart'
    as _i6;
import 'package:food_recipe/features/splash/presentation/controllers/splash_controller.dart'
    as _i10;
import 'package:get/get.dart' as _i7;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i11;
import 'package:get_storage/get_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetStorage_0 extends _i1.SmartFake implements _i2.GetStorage {
  _FakeGetStorage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSplashRepository_2 extends _i1.SmartFake
    implements _i4.SplashRepository {
  _FakeSplashRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSplashRepositoryImpl_3 extends _i1.SmartFake
    implements _i5.SplashRepositoryImpl {
  _FakeSplashRepositoryImpl_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageGetUser_4 extends _i1.SmartFake
    implements _i6.StorageGetUser {
  _FakeStorageGetUser_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_5<T> extends _i1.SmartFake
    implements _i7.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageUser extends _i1.Mock implements _i8.StorageUser {
  @override
  String get spKey => (super.noSuchMethod(
        Invocation.getter(#spKey),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#spKey),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#spKey),
        ),
      ) as String);

  @override
  _i2.GetStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeGetStorage_0(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeGetStorage_0(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.GetStorage);

  @override
  _i3.User get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _FakeUser_1(
          this,
          Invocation.method(
            #get,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUser_1(
          this,
          Invocation.method(
            #get,
            [],
          ),
        ),
      ) as _i3.User);

  @override
  void save(_i3.User? value) => super.noSuchMethod(
        Invocation.method(
          #save,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageGetUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageGetUser extends _i1.Mock implements _i6.StorageGetUser {
  @override
  _i4.SplashRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeSplashRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeSplashRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.SplashRepository);

  @override
  _i3.User execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _FakeUser_1(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUser_1(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        ),
      ) as _i3.User);
}

/// A class which mocks [SplashController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplashController extends _i1.Mock implements _i10.SplashController {
  @override
  _i5.SplashRepositoryImpl get repo => (super.noSuchMethod(
        Invocation.getter(#repo),
        returnValue: _FakeSplashRepositoryImpl_3(
          this,
          Invocation.getter(#repo),
        ),
        returnValueForMissingStub: _FakeSplashRepositoryImpl_3(
          this,
          Invocation.getter(#repo),
        ),
      ) as _i5.SplashRepositoryImpl);

  @override
  _i6.StorageGetUser get storageGetUser => (super.noSuchMethod(
        Invocation.getter(#storageGetUser),
        returnValue: _FakeStorageGetUser_4(
          this,
          Invocation.getter(#storageGetUser),
        ),
        returnValueForMissingStub: _FakeStorageGetUser_4(
          this,
          Invocation.getter(#storageGetUser),
        ),
      ) as _i6.StorageGetUser);

  @override
  set storageGetUser(_i6.StorageGetUser? _storageGetUser) => super.noSuchMethod(
        Invocation.setter(
          #storageGetUser,
          _storageGetUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i7.InternalFinalCallback<void>);

  @override
  _i7.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i7.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onLoad(_i3.User? user) => super.noSuchMethod(
        Invocation.method(
          #onLoad,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Disposer addListener(_i11.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i11.Disposer);

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i12.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Disposer addListenerId(
    Object? key,
    _i11.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i11.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
